// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	Domain "main/Domain"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// Login provides a mock function with given fields: c, user
func (_m *AuthUseCase) Login(c *gin.Context, user *Domain.User) (string, error, int) {
	ret := _m.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	var r2 int
	if rf, ok := ret.Get(0).(func(*gin.Context, *Domain.User) (string, error, int)); ok {
		return rf(c, user)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *Domain.User) string); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *Domain.User) error); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(*gin.Context, *Domain.User) int); ok {
		r2 = rf(c, user)
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: c, user
func (_m *AuthUseCase) Register(c *gin.Context, user *Domain.User) (Domain.OmitedUser, error, int) {
	ret := _m.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 Domain.OmitedUser
	var r1 error
	var r2 int
	if rf, ok := ret.Get(0).(func(*gin.Context, *Domain.User) (Domain.OmitedUser, error, int)); ok {
		return rf(c, user)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, *Domain.User) Domain.OmitedUser); ok {
		r0 = rf(c, user)
	} else {
		r0 = ret.Get(0).(Domain.OmitedUser)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, *Domain.User) error); ok {
		r1 = rf(c, user)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(*gin.Context, *Domain.User) int); ok {
		r2 = rf(c, user)
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
